version: "3.8"
services:
  app-backend:
    container_name: Server-DB
    platform: linux/x86_64
    image: appbackend:latest
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public
      - /app/node_modules

    ports:
      - "3000:3000"
    env_file:
      - ./.env/postgres.env
      - ./.env/SMTP.env
      - ./.env/maildev.env
      - ./.env/backend.env
    depends_on:
      - db
    command: npm run start:dev

  app-frontend:
    container_name: Server-FRONT
    platform: linux/x86_64
    image: appfrontend:latest
    build:
      context: ./frontend
    env_file:
      - ./.env/frontend.env
    ports:
      - "8080:8081"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/.svelte-kit:/app/.svelte-kit
      - ./frontend/static:/app/static
      - /app/node_modules
    depends_on:
      - app-backend
    command: npm run dev --host

  db:
    container_name: postgres_quizz
    image: postgres:latest
    restart: always
    env_file:
      - ./.env/postgres.env
    volumes:
      - ./backend/DataBase/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      - ./backend/DataBase/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/DataBase/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer_quizz
    image: adminer:latest
    restart: always
    ports:
      - "5051:8080"
    env_file:
      - ./.env/postgres.env
      - ./.env/adminer.env
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin_quizz
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - ./.env/postgres.env
      - ./.env/pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres-data:
