version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - ./.env/postgres.env
    volumes:
      # - ${PWD}/DataBase/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./DataBase/postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  adminer:
    container_name: adminer_quizz
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: 'db'
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4-demo
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
